#
# This file is part of the ArtCovid distribution (https://github.com/nschaetti).
# Copyright (c) 2021 Nils Schaetti.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# Imports file schemas
from .constants import SWISSDATA_SCHEMA_FILES

# Imports enum
from .constants import SWISSDATA_LOCATION_ENUM, SWISSDATA_SEVERITY_ENUM, SWISSDATA_INT_GEOLEVEL_ENUM, \
    SWISSDATA_VACCINE_ENUM, SWISSDATA_INT_GEOLEVEL_ENUM, SWISSDATA_INDICATION_ENUM, SWISSDATA_VACC_PERSONS_ENUM, \
    SWISSDATA_SEX_ENUM, SWISSDATA_SOURCE_ENUM, SWISSDATA_GEOREGIONS_ENUM, SWISSDATA_GRANULARITY_ENUM, \
    SWISSDATA_GEOREGION_TYPE_ENUM, SWISSDATA_CLASSIFICATION_ENUM, SWISSDATA_AGE_GROUP_TYPE_ENUM, \
    SWISSDATA_TYPE_ENUM, SWISSDATA_COMPLETENESS_ENUM, SWISSDATA_DATUM_UNIT_ENUM, SWISSDATA_WEEKLY_REPORT_ENUM, \
    SWISSDATA_NACHWEISMETHODE_ENUM, SWISSDATA_VACCINATION_STATUS_ENUM, SWISSDATA_VACCINATION_AGE_RANGE_ENUM, \
    SWISSDATA_VACC_PERSONS_AGE_GROUP_ENUM, SWISSDATA_INCOMING_AGE_RANGE_ENUM, SWISSDATA_VACCINE_VARIANT_TYPE_ENUM, \
    SWISSDATA_INZ_CATEGORY_NORMALIZED_ENUM, SWISSDATA_VIRUS_VARIANT_WGS_TYPE_ENUM

# Imports fields
from .constants import SWISSDATA_FLOAT_FIELD, SWISSDATA_INTEGER_FIELD, SWISSDATA_VERSION_FIELD, \
    SWISSDATA_VACCINE_FIELD, SWISSDATA_GEOREGIONS_FIELD, SWISSDATA_GRANULARITY_FIELD, SWISSDATA_INDICATION_FIELD, \
    SWISSDATA_SEX_FIELD, SWISSDATA_LOCATION_FIELD, SWISSDATA_BOOLEAN_FIELD, SWISSDATA_DATE_YYYYMMDD_FIELD, \
    SWISSDATA_SOURCE_FIELD, SWISSDATA_INT_GEOLEVEL_FIELD, SWISSDATA_STRING_FIELD, SWISSDATA_DATETIME_FIELD, \
    SWISSDATA_VACC_PERSONS_FIELD, SWISSDATA_COMPLETENESS_FIELD, SWISSDATA_DATUM_UNIT_FIELD, \
    SWISSDATA_NACHWEISMETHODE_FIELD, SWISSDATA_DATE_ISOWEEK_FIELD, SWISSDATA_GEOREGION_TYPE_FIELD, \
    SWISSDATA_VACCINATION_STATUS_FIELD, SWISSDATA_SEVERITY_FIELD, SWISSDATA_VARIANT_TYPE_FIELD, \
    SWISSDATA_CLASSIFICATION_FIELD, SWISSDATA_AGE_GROUP_TYPE_FIELD, SWISSDATA_INCOMING_AGE_RANGE_FIELD, \
    SWISSDATA_INZ_CATEGORY_NORMALIZED_FIELD, SWISSDATA_DATE_ISOWEEK_STR_FIELD, SWISSDATA_VACCINE_VARIANT_TYPE_FIELD, \
    SWISSDATA_VACCINATION_AGE_RANGE_FIELD, SWISSDATA_VACC_PERSONS_AGE_GROUP_FIELD

# Imports properties
from .constants import SWISSDATA_HOSP_VACC_PERSONS_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACC_PERSONS_WEEKLY_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_WEEKLY_DEATH_VACC_PERSONS_AGE_RANGE_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_WEEKLY_HOSP_VACC_PERSONS_AGE_RANGE_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACC_PERSONS_WEEKLY_AGE_RANGE_VACCINE_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_HOSP_CAPACITY_DAILY_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_REDAILY_INCOMING_DATA_PROPERTIES, SWISSDATA_VACCINATION_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACC_PERSONS_INCOMING_DATA_PROPERTIES, SWISSDATA_VACC_PERSONS_WEEKLY_INDICATION_INCOMING_DATA_PROPERTIES,\
    SWISSDATA_WEEKLY_INCOMING_DATA_PROPERTIES, SWISSDATA_VACCINATION_WEEKLY_INDICATION_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACC_PERSONS_VACCINE_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_CONTACT_TRACING_INCOMING_DATA_PROPERTIES, SWISSDATA_INTERNATIONAL_QUARANTINE_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_COVID_CERTIFICATE_DAILY_INCOMING_DATA_PROPERTIES, SWISSDATA_INTERNATIONAL_DAILY_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_DAILY_REPORT_INCOMING_DATA_PROPERTIES, SWISSDATA_VACCINATION_CONTINGENT_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACCINATION_SYMPTOMS_INCOMING_DATA_PROPERTIES, SWISSDATA_WEEKLY_REPORT_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACCINATION_WEEKLY_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACCINATION_WEEKLY_LOCATION_INCOMING_DATA_PROPERTIES, SWISSDATA_DAILY_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_DAILY_DEATH_VACC_PERSONS_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_WEEKLY_HOSP_VACC_PERSONS_SEX_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_ADDITIONAL_GEO_REGION_DAILY_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VIRUS_VARIANTS_WGS_DAILY_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACCINATION_DOSES_RECEIVED_DELIVERED_VACCINE_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_ADDITIONAL_GEO_REGION_14D_PERIOD_INCOMING_DATA_PROPERTIES, \
    SWISSDATA_VACCINATION_VACCINE_INCOMING_DATA_PROPERTIES

# Imports data descriptions
from .constants import SWISSDATA_DATA_DESCRIPTION

# Utility functions
from .tools import swissdata_dataset_to_h5, download_swissdata_dataset, extract_models_definitions, \
    clean_dataset_directory

# ALL
__all__ = [
    # Schemas
    'SWISSDATA_SCHEMA_FILES',
    # Enums
    'SWISSDATA_LOCATION_ENUM', 'SWISSDATA_SEVERITY_ENUM', 'SWISSDATA_INT_GEOLEVEL_ENUM',
    'SWISSDATA_VACCINE_ENUM', 'SWISSDATA_INT_GEOLEVEL_ENUM', 'SWISSDATA_INDICATION_ENUM', 'SWISSDATA_VACC_PERSONS_ENUM',
    'SWISSDATA_SEX_ENUM', 'SWISSDATA_SOURCE_ENUM', 'SWISSDATA_GEOREGIONS_ENUM', 'SWISSDATA_GRANULARITY_ENUM',
    'SWISSDATA_GEOREGION_TYPE_ENUM', 'SWISSDATA_CLASSIFICATION_ENUM', 'SWISSDATA_AGE_GROUP_TYPE_ENUM',
    'SWISSDATA_TYPE_ENUM', 'SWISSDATA_COMPLETENESS_ENUM', 'SWISSDATA_DATUM_UNIT_ENUM', 'SWISSDATA_WEEKLY_REPORT_ENUM',
    'SWISSDATA_NACHWEISMETHODE_ENUM', 'SWISSDATA_VACCINATION_STATUS_ENUM', 'SWISSDATA_VACCINATION_AGE_RANGE_ENUM',
    'SWISSDATA_VACC_PERSONS_AGE_GROUP_ENUM', 'SWISSDATA_INCOMING_AGE_RANGE_ENUM', 'SWISSDATA_VACCINE_VARIANT_TYPE_ENUM',
    'SWISSDATA_INZ_CATEGORY_NORMALIZED_ENUM', 'SWISSDATA_VIRUS_VARIANT_WGS_TYPE_ENUM',
    # Fields
    'SWISSDATA_FLOAT_FIELD', 'SWISSDATA_INTEGER_FIELD', 'SWISSDATA_VERSION_FIELD',
    'SWISSDATA_VACCINE_FIELD', 'SWISSDATA_GEOREGIONS_FIELD', 'SWISSDATA_GRANULARITY_FIELD',
    'SWISSDATA_INDICATION_FIELD',
    'SWISSDATA_SEX_FIELD', 'SWISSDATA_LOCATION_FIELD', 'SWISSDATA_BOOLEAN_FIELD', 'SWISSDATA_DATE_YYYYMMDD_FIELD',
    'SWISSDATA_SOURCE_FIELD', 'SWISSDATA_GEOLEVEL_FIELD', 'SWISSDATA_STRING_FIELD', 'SWISSDATA_DATETIME_FIELD',
    'SWISSDATA_VACC_PERSONS_FIELD', 'SWISSDATA_COMPLETENESS_FIELD', 'SWISSDATA_DATUM_UNIT_FIELD',
    'SWISSDATA_NACHWEISMETHODE_FIELD', 'SWISSDATA_DATE_ISOWEEK_FIELD', 'SWISSDATA_GEOREGION_TYPE_FIELD',
    'SWISSDATA_VACCINATION_STATUS_FIELD', 'SWISSDATA_SEVERITY_FIELD', 'SWISSDATA_VARIANT_TYPE_FIELD',
    'SWISSDATA_CLASSIFICATION_FIELD', 'SWISSDATA_AGE_GROUP_TYPE_FIELD', 'SWISSDATA_INCOMING_AGE_RANGE_FIELD',
    'SWISSDATA_INZ_CATEGORY_NORMALIZED_FIELD', 'SWISSDATA_DATE_ISOWEEK_STR_FIELD',
    'SWISSDATA_VACCINE_VARIANT_TYPE_FIELD',
    'SWISSDATA_VACCINATION_AGE_RANGE_FIELD', 'SWISSDATA_VACC_PERSONS_AGE_GROUP_FIELD',
    # Properties
    'SWISSDATA_HOSP_VACC_PERSONS_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACC_PERSONS_WEEKLY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_WEEKLY_DEATH_VACC_PERSONS_AGE_RANGE_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_WEEKLY_HOSP_VACC_PERSONS_AGE_RANGE_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACC_PERSONS_WEEKLY_AGE_RANGE_VACCINE_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_HOSP_CAPACITY_DAILY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_REDAILY_INCOMING_DATA_PROPERTIES', 'SWISSDATA_VACCINATION_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACC_PERSONS_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACC_PERSONS_WEEKLY_INDICATION_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_WEEKLY_INCOMING_DATA_PROPERTIES', 'SWISSDATA_VACCINATION_WEEKLY_INDICATION_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACC_PERSONS_VACCINE_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_CONTACT_TRACING_INCOMING_DATA_PROPERTIES', 'SWISSDATA_INTERNATIONAL_QUARANTINE_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_COVID_CERTIFICATE_DAILY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_INTERNATIONAL_DAILY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_DAILY_REPORT_INCOMING_DATA_PROPERTIES', 'SWISSDATA_VACCINATION_CONTINGENT_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACCINATION_SYMPTOMS_INCOMING_DATA_PROPERTIES', 'SWISSDATA_WEEKLY_REPORT_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACCINATION_WEEKLY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACCINATION_WEEKLY_LOCATION_INCOMING_DATA_PROPERTIES', 'SWISSDATA_DAILY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_DAILY_DEATH_VACC_PERSONS_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_WEEKLY_HOSP_VACC_PERSONS_SEX_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_ADDITIONAL_GEO_REGION_DAILY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VIRUS_VARIANTS_WGS_DAILY_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACCINATION_DOSES_RECEIVED_DELIVERED_VACCINE_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_ADDITIONAL_GEO_REGION_14D_PERIOD_INCOMING_DATA_PROPERTIES',
    'SWISSDATA_VACCINATION_VACCINE_INCOMING_DATA_PROPERTIES',
    # Data description
    'SWISSDATA_DATA_DESCRIPTION',
    # Utility functions
    'swissdata_dataset_to_h5', 'download_swissdata_dataset', 'extract_models_definitions',
    'clean_dataset_directory'
]
